export interface Creator {
  id: string;
  name: string;
  image: string;
  price: number;
  country: string;
  followers: number;
  languages: string[];
  isOnline: boolean;
  randomMatchEnabled: boolean;
  allowedCallTypes: "audio" | "video" | "both";
  aboutMe?: string;
  talksAbout?: string[];
  hobbies?: string[];
  foodPreferences?: string[];
  sportsInterests?: string[];
  mediaImages: string[];
  mediaVideo?: string;
}

const creatorProfiles: Omit<Creator, "image">[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    price: 45,
    country: "India",
    followers: 1250,
    languages: ["English", "Hindi", "Tamil"],
    isOnline: true,
    randomMatchEnabled: true,
    allowedCallTypes: "both",
    aboutMe: "Friendly conversationalist who loves discussing life experiences and offering advice on personal growth.",
    talksAbout: ["Life coaching", "Relationships", "Career guidance", "Mental wellness"],
    hobbies: ["Reading", "Yoga", "Traveling", "Cooking"],
    foodPreferences: ["Vegetarian", "Italian cuisine", "Indian sweets"],
    sportsInterests: ["Cricket", "Badminton", "Running"],
    mediaImages: [
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&h=800&fit=crop",
    ],
    mediaVideo: "https://storage.coverr.co/videos/coverr-woman-smiling-at-camera-8031/preview",
  },
  {
    id: "2",
    name: "Rahul Verma",
    price: 38,
    country: "India",
    followers: 890,
    languages: ["Hindi", "English"],
    isOnline: false,
    randomMatchEnabled: false,
    allowedCallTypes: "video",
    aboutMe: "Tech enthusiast and startup mentor with 10 years of experience in software development.",
    talksAbout: ["Technology", "Startups", "Programming", "Career advice"],
    hobbies: ["Gaming", "Photography", "Blogging"],
    foodPreferences: ["Non-vegetarian", "North Indian", "Chinese"],
    sportsInterests: ["Football", "Chess", "Table tennis"],
    mediaImages: [
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&h=800&fit=crop",
    ],
    mediaVideo: "https://storage.coverr.co/videos/coverr-working-on-a-laptop-1571/preview",
  },
  {
    id: "3",
    name: "Priya Sharma",
    price: 52,
    country: "India",
    followers: 2100,
    languages: ["English", "Hindi", "Marathi"],
    isOnline: true,
    randomMatchEnabled: true,
    allowedCallTypes: "both",
    aboutMe: "Business consultant and motivational speaker passionate about empowering entrepreneurs.",
    talksAbout: ["Business strategy", "Entrepreneurship", "Marketing", "Leadership"],
    hobbies: ["Public speaking", "Writing", "Gardening"],
    foodPreferences: ["Vegetarian", "South Indian", "Continental"],
    sportsInterests: ["Tennis", "Swimming", "Cycling"],
    mediaImages: [
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&h=800&fit=crop",
    ],
    mediaVideo: "https://storage.coverr.co/videos/coverr-businesswoman-smiling-4284/preview",
  },
  {
    id: "4",
    name: "Amit Patel",
    price: 40,
    country: "India",
    followers: 1500,
    languages: ["Gujarati", "Hindi", "English"],
    isOnline: true,
    randomMatchEnabled: false,
    allowedCallTypes: "audio",
    aboutMe: "Finance expert helping people make smart investment decisions and achieve financial freedom.",
    talksAbout: ["Investment", "Stock market", "Personal finance", "Real estate"],
    hobbies: ["Reading", "Playing guitar", "Hiking"],
    foodPreferences: ["Vegetarian", "Gujarati cuisine", "Street food"],
    sportsInterests: ["Cricket", "Volleyball", "Jogging"],
    mediaImages: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=800&h=800&fit=crop",
    ],
    mediaVideo: "https://storage.coverr.co/videos/coverr-man-talking-on-the-phone-3701/preview",
  },
  {
    id: "5",
    name: "Neha Kapoor",
    price: 48,
    country: "India",
    followers: 1780,
    languages: ["English", "Hindi", "Punjabi"],
    isOnline: true,
    randomMatchEnabled: true,
    allowedCallTypes: "both",
    aboutMe: "Fashion designer and lifestyle blogger who loves sharing creative ideas and style tips.",
    talksAbout: ["Fashion", "Lifestyle", "Beauty", "Social media"],
    hobbies: ["Sketching", "Shopping", "Dancing", "Photography"],
    foodPreferences: ["Vegetarian", "Punjabi cuisine", "Fusion food"],
    sportsInterests: ["Zumba", "Yoga", "Badminton"],
    mediaImages: [
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=800&h=800&fit=crop",
    ],
    mediaVideo: "https://storage.coverr.co/videos/coverr-fashion-model-3155/preview",
  },
  {
    id: "6",
    name: "Vikram Singh",
    price: 35,
    country: "India",
    followers: 750,
    languages: ["Hindi", "English"],
    isOnline: false,
    randomMatchEnabled: false,
    allowedCallTypes: "video",
    aboutMe: "Fitness trainer and nutrition coach dedicated to helping people achieve their health goals.",
    talksAbout: ["Fitness", "Nutrition", "Weight loss", "Muscle building"],
    hobbies: ["Gym training", "Sports", "Cooking healthy meals"],
    foodPreferences: ["High protein", "Salads", "Smoothies"],
    sportsInterests: ["Bodybuilding", "Boxing", "Running", "Basketball"],
    mediaImages: [
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1531891437562-4301cf35b7e4?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=800&h=800&fit=crop",
    ],
    mediaVideo: "https://storage.coverr.co/videos/coverr-man-doing-workout-2635/preview",
  },
  {
    id: "7",
    name: "Anjali Mehta",
    price: 42,
    country: "India",
    followers: 1320,
    languages: ["English", "Hindi", "Bengali"],
    isOnline: true,
    randomMatchEnabled: true,
    allowedCallTypes: "audio",
    aboutMe: "Psychologist and counselor specializing in stress management and emotional well-being.",
    talksAbout: ["Mental health", "Stress management", "Relationships", "Self-care"],
    hobbies: ["Meditation", "Reading", "Painting", "Listening to music"],
    foodPreferences: ["Vegetarian", "Bengali cuisine", "Organic food"],
    sportsInterests: ["Walking", "Swimming", "Yoga"],
    mediaImages: [
      "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1548142813-c348350df52b?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=800&h=800&fit=crop",
    ],
    mediaVideo: "https://storage.coverr.co/videos/coverr-woman-meditating-1584/preview",
  },
  {
    id: "8",
    name: "Karan Malhotra",
    price: 50,
    country: "India",
    followers: 1950,
    languages: ["Hindi", "English", "Urdu"],
    isOnline: true,
    randomMatchEnabled: false,
    allowedCallTypes: "both",
    aboutMe: "Digital marketing expert helping brands grow their online presence and reach their audience.",
    talksAbout: ["Digital marketing", "SEO", "Content creation", "Brand building"],
    hobbies: ["Traveling", "Photography", "Blogging", "Music"],
    foodPreferences: ["Non-vegetarian", "Mughlai", "Italian"],
    sportsInterests: ["Cricket", "Football", "Snooker"],
    mediaImages: [
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=800&h=800&fit=crop",
    ],
    mediaVideo: "https://storage.coverr.co/videos/coverr-man-with-camera-4985/preview",
  },
  {
    id: "9",
    name: "Kavya Iyer",
    price: 46,
    country: "India",
    followers: 1650,
    languages: ["English", "Tamil", "Hindi"],
    isOnline: false,
    randomMatchEnabled: false,
    allowedCallTypes: "video",
    aboutMe: "Classical dancer and arts enthusiast sharing insights on Indian culture and performing arts.",
    talksAbout: ["Dance", "Indian culture", "Arts", "Music", "Traditions"],
    hobbies: ["Dancing", "Teaching", "Traveling", "Cooking"],
    foodPreferences: ["Vegetarian", "South Indian", "Traditional sweets"],
    sportsInterests: ["Badminton", "Swimming", "Yoga"],
    mediaImages: [
      "https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1512316609839-ce289d3eba0a?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1517365830460-955ce3ccd263?w=800&h=800&fit=crop",
    ],
    mediaVideo: "https://storage.coverr.co/videos/coverr-woman-dancing-5550/preview",
  },
];

export const creatorsData: Creator[] = creatorProfiles.map((creator) => ({
  ...creator,
  image: creator.mediaImages[0],
}));
